config/routes.rb
Rails.application.routes.draw do

  root 'perfect_shifts#index'
  get '/help',      to: 'static_pages#help'
  get  '/signup',   to: 'masters#new'
  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  post '/logout',    to:'sessions#destroy'

  resources :masters do
    patch     :shift_onoff   , on: :collection
    resources :shift_separations, :except => [:show]

    member do
      get :login,  to: 'masters#login_form'
      post :login, to: 'masters#login'
      delete :logout
    end
  end

  resources :staffs 

  resources :notices, :only => [:index, :show, :destroy, :update] do
    # patch :deny, on: :member
  end

  # get :chnage_form,      to: 'perfect_shifts#change_form'
  # patch :change,         to: 'perfect_shifts#change'

  resources :perfect_shifts, :only => [:index] do
    collection do
      get :fill
      get :change
      get :new_plan
      post :create_plan
    end

    member do
      patch :fill_in
      patch :instead
      patch :delete
    end
  end

  get :comfirmed_shifts,  to: 'comfirmed_shifts#index'

  resources :temporary_shifts , :only => [:index, :destroy] do
    collection do
      get :new_shift
      get :new_plan
      post :create_shift
      post :create_plan
      get  :delete
      patch :perfect
    end
    
    member do
      patch :deletable
    end
  end

  resources :deletable_shifts, :only => [:index] do
    get :restore , on: :collection
    patch :reborn, on: :member
  end
  
  resources :individual_shifts do
    
    collection do
      # patch  :confirm,  to: 'individual_shifts#confirm'
      patch  :perfect
      get  :remove
      post :finish
    end

    member do
      patch :deletable, to: 'individual_shifts#deletable'
    end
  end

end

app/models/shift_separation.rb
class ShiftSeparation < ApplicationRecord
  belongs_to :master
  default_scope -> { order(start_time: :asc) }
  validates :name, presence: true, uniqueness: true
  validates :start_time, presence: true
  validates :finish_time, presence: true
  validate  :start_end_check
  
  #start_timeとfinish_timeの大小関係を制限(start < finish => true)
  #正し、夜勤の時間帯設定(21時~)にはこの制限を解除する
  def start_end_check
    if self.start_time.present? && self.finish_time.present?
      errors.add(:finish_time, "が開始時刻を上回っています。正しく記入してください。") if self.start_time > self.finish_time && self.start_time.hour < 21
    end
  end

  #空きシフトの自動入力に使う
  def start_h
    if self.start_time.hour < 10
      "0#{self.start_time.hour}"
    else
      self.start_time.hour
    end
  end

  #空きシフトの自動入力に使う
  def finish_h
    if self.finish_time.hour < 10
      "0#{self.finish_time.hour}"
    else
      self.finish_time.hour
    end
  end

  #新人従業員ようにナビを表示するためにシフト時間割の時刻を返す
  def start_to_finish
    "#{self.start_time.strftime("%H:%M")}-#{self.finish_time.strftime("%H:%M")}"
  end

end

app/controllers/shift_separations_controller.rb
class ShiftSeparationsController < ApplicationController
    before_action :logged_in_master, except: [:destroy]
    before_action :corrent_master,   except: [:destroy]

    #シフトの時間割のcrud機能

    def new
        @shift_separation = current_master.shift_separations.new
    end

    def create
        @shift_separation = current_master.shift_separations.new(separation_params)
        if @shift_separation.save 
            flash[:success] = "シフトコマを作成完了しました！"
            redirect_to root_path
        else
            render 'new'
        end
    end

    def index
        @shift_separations = current_master.shift_separations.all
    end

    def edit
        @shift_separation = current_master.shift_separations.find(params[:id])
    end

    def update
        @shift_separation = current_master.shift_separations.find(params[:id])
        if @shift_separation.update(separation_params)
            flash[:success] = "変更完了しました！"
            redirect_to master_shift_separations_path
        else
            render 'edit'
        end
    end

    def destroy
        current_master.shift_separations.find(params[:id]).destroy
        flash[:success] = "削除しました"
        redirect_to master_shift_separations_path
    end

    private 
      def separation_params
        params.require(:shift_separation).permit(:name, :start_time, :finish_time)
      end

      def corrent_master
        @master = Master.find(params[:master_id])
        redirect_to(root_url) unless current_master?(@master)
      end
end

app/helpers/shift_separations_helper.rb
module ShiftSeparationsHelper
end

app/views/shift_separations/edit.html.erb
<div class="wrapper"> 
   <h1>シフト時間割を変更</h1>

   <div class="row">
      <div class="col-md-6 col-md-offset-3">
         <%= form_with(method: :patch, url: master_shift_separation_url, scope: :shift_separation, local: true) do |f| %>
            <%= render 'shared/error_messages', object: @shift_separation %>

            <%= f.label :name,"時間帯名" %>
            <%= f.text_field :name, class: 'form-control' %>
         <div class="form-inline text-left">
            <%= f.label :start_time,"業務開始時刻", {class:'control-label'}%>
            <%= f.time_field :start_time, class: 'form-control' %>

            <%= f.label :finish_time,"業務終了時刻", {class:'control-label'}%>
            <%= f.time_field :finish_time, class: 'form-control' %>
         </div>
            <%= f.submit "登録", class: "btn btn-primary" %>
         <% end %>
      </div>
   </div>
</div>        

app/views/shift_separations/index.html.erb
<div class="wrapper">  
  <section class="info">   
    <h1>シフト時間割の一覧</h1>
      <ul>
          <% @shift_separations.each do |shift_separation| %>
              <li> 
                <%= link_to shift_separation.name, edit_master_shift_separation_path(current_master,shift_separation) %>　  
                <%= shift_separation.start_h %>  時　~　<%= shift_separation.finish_h %> 時　
                <%= link_to "編集",edit_master_shift_separation_path(current_master, shift_separation)%>
                <%= link_to "削除",master_shift_separation_path(current_master,shift_separation) ,
                {method: :delete, data: { confirm: 'この時間帯を削除して間違いありませんか？'}, class:"delete"} %>
              </li>
          <% end %>   
      </ul>
  </section>
</div>        

app/views/shift_separations/new.html.erb
<div class="wrapper">  
   <h1>シフト時間割を追加</h1>

   <div class="row">
      <div class="col-md-6 col-md-offset-3">
         <%= form_with(url: master_shift_separations_path, scope: :shift_separation, local: true) do |f| %>
            <%= render 'shared/error_messages', object: @shift_separation %>

            <%= f.label :name,"時間帯名" %>
            <%= f.text_field :name, class: 'form-control' %>
         <div class="form-inline text-left">
            <%= f.label :start_time,"業務開始時刻", {class:'control-label'}%>
            <%= f.time_field :start_time, class: 'form-control' %>

            <%= f.label :finish_time,"業務終了時刻", {class:'control-label'}%>
            <%= f.time_field :finish_time, class: 'form-control' %>
         </div>
            <%= f.submit "登録",   class: "btn btn-primary" %>
         <% end %>
      </div>
   </div>        
</div>