config/routes.rb
Rails.application.routes.draw do

  root 'perfect_shifts#index'
  get '/help',      to: 'static_pages#help'
  get  '/signup',   to: 'masters#new'
  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  post '/logout',    to:'sessions#destroy'

  resources :masters do
    patch     :shift_onoff   , on: :collection
    resources :shift_separations, :except => [:show]

    member do
      get :login,  to: 'masters#login_form'
      post :login, to: 'masters#login'
      delete :logout
    end
  end

  resources :staffs 

  resources :notices, :only => [:index, :show, :destroy, :update] do
    # patch :deny, on: :member
  end

  # get :chnage_form,      to: 'perfect_shifts#change_form'
  # patch :change,         to: 'perfect_shifts#change'

  resources :perfect_shifts, :only => [:index] do
    collection do
      get :fill
      get :change
      get :new_plan
      post :create_plan
    end

    member do
      patch :fill_in
      patch :instead
      patch :delete
    end
  end

  get :comfirmed_shifts,  to: 'comfirmed_shifts#index'

  resources :temporary_shifts , :only => [:index, :destroy] do
    collection do
      get :new_shift
      get :new_plan
      post :create_shift
      post :create_plan
      get  :delete
      patch :perfect
    end
    
    member do
      patch :deletable
    end
  end

  resources :deletable_shifts, :only => [:index] do
    get :restore , on: :collection
    patch :reborn, on: :member
  end
  
  resources :individual_shifts do
    
    collection do
      # patch  :confirm,  to: 'individual_shifts#confirm'
      patch  :perfect
      get  :remove
      post :finish
    end

    member do
      patch :deletable, to: 'individual_shifts#deletable'
    end
  end

end

app/models/individual_shift.rb
class IndividualShift < ApplicationRecord
  belongs_to :staff

  has_one :master, through: :staff

  default_scope -> { order(start: :asc) }
  validate  :start_end_check
  
  #startとfinishの大小関係を制限(start < finish => true)
  #正し、夜勤の時間帯設定(21時~)にはこの制限を解除する
  def start_end_check
    if self.start.present? && self.finish.present?
      errors.add(:finish, "が開始時刻を上回っています。正しく記入してください。") if self.start.hour >= self.finish.hour && self.start.hour <= 21
    end
  end

  #カレンダーで表示する名前
  def parent
    if self.staff.staff_number == 0
      if self.plan == nil
        " "
      else
        self.plan
      end
    else
      self.staff.staff_name
    end
    
  end

  #終日判定
  def allDay
    unless self.finish.present?
      true
    else
      false
    end
  end

  #トレーニング中の従業員の枠線は赤にする
  def color
    if self.staff.training_mode == true
      "red"
    else
      "black"
    end
  end

  def fulltime
    str = [ "#{self.start.strftime("%m/%d %H")}" + "時", "#{self.finish.strftime("%H")}" + "時" ]
    return str.join(" ~ ")
  end

  #個人シフト提出中に表示する時刻
  def time
    str = [ "#{self.start.strftime("%H")}", "#{self.finish.strftime("%H")}" ]
    return str.join(" ~ ")
    
  end

  #空きシフトは背景を黄色で表示
  def backgroundColor
    if self.staff.staff_number == 0 && self.finish != nil
      "yellow"
    else
      "white"
    end
  end
end

app/controllers/individual_shifts_controller.rb
class IndividualShiftsController < ApplicationController
    before_action :logged_in_staff, except: [:destroy]

    require 'date'

    def index
        #このページで全てのアクションを実行していく
        @events = current_staff.individual_shifts.where(Temporary: false)
        @shift_separation = current_staff.master.shift_separations.all
    end

    def new
        @event = current_staff.individual_shifts.new
        @patterns = current_staff.patterns.all
        #新規作成のmodal用のhtmlを返す
        render plain: render_to_string(partial: 'form_new', layout: false, locals: { event: @event, patterns: @patterns })
    end

    def create
        @event = current_staff.individual_shifts.new(params_event)
        #日付を自動調整
        change_finishDate 
        #同じ時間のシフトを捜索
        @already_event = current_staff.individual_shifts.where(start:@event.start).where(finish:@event.finish)
        
        #シフトパターンを作成
        @pattern = current_staff.patterns.new(params_event) 
        @already_pattern = current_staff.patterns.where(start: @pattern.start).where(finish: @pattern.finish)
        
        #すでに同じシフトを登録していないか判定
        unless @already_event.present?
            if @event.save  
                #過去に同じ時間帯に登録したことがなければ新しい登録パターンを追加
                unless @already_pattern.present?
                    @pattern.save
                end
            else
                respond_to do |format|
                    format.js {render partial: "error" }
                end
            end
        else
            #被りエラーを表示する
            respond_to do |format|
                format.js {render partial: "duplicate" }
            end        
        end 
    end 


    def remove
        @event = current_staff.individual_shifts.find(params[:shift_id])
        return_html("form_delete")
    end


    def destroy
        #両方でログイン中
        if logged_in_staff? && logged_in?
            @event = current_master.individual_shifts.find(params[:id]).destroy
        #従業員のみログイン中
        elsif logged_in_staff? && !logged_in?
            @event = current_staff.individual_shifts.find(params[:id]).destroy
        #店長のみログイン中
        elsif logged_in? && !logged_in_staff?
            @event = current_master.individual_shifts.find(params[:id]).destroy
        end
    end

    def finish
        flash[:success] = "登録を終了しました！"
        redirect_to root_path
    end


    private
      def params_event
        params.require(:individual_shift).permit(:start, :finish)
      end
end

app/helpers/individual_shifts_helper.rb
module IndividualShiftsHelper
    #退勤時間の日付を出勤時間の日付に合わせる
    def change_finishDate 
        #日付を跨がない場合はそのまま,日付を跨ぐ場合は1日プラスする。
        if @event.start.hour > @event.finish.hour  
            last_day = Date.new(@event.start.year,@event.start.month,-1).day #月末の日にちを取得
            if @event.start.month == 12 && @event.start.day == 31            #大晦日
                @event.finish = @event.finish.change(year: @event.start.year + 1 ,  month: 1, day: 1)
            elsif !(@event.start.month == 12) && @event.start.day == last_day #普通の月末
                @event.finish = @event.finish.change(year: @event.start.year,  month: @event.start.month + 1, day: 1)
            else #月末でもない日
                @event.finish = @event.finish.change(year: @event.start.year,  month: @event.start.month,     day: @event.start.day + 1)
            end
        end
      end
end

app/views/individual_shifts/_duplicate.js.erb
$('.response-modal-body').html('<h1>同じ時間のシフトがすでに登録されています！</h1>');
$('#response-modal').fadeIn();

app/views/individual_shifts/_error.js.erb
$('.response-modal-body').html('<h1>時間設定が間違っています！</h1>');
$('#response-modal').fadeIn();

app/views/individual_shifts/_form_delete.html.erb
<h1><%= @event.fulltime %></h1>

<div class="row">
    <%= form_with(model: @event, url: individual_shift_path(@event), html: { method: :delete }, remote: true) do |f| %>
        <%= f.submit "消去", class: "btn btn-primary" %>
    <% end %>
</div>    

app/views/individual_shifts/_form_new.html.erb
<h1>新規シフト</h1>

<div class="row">
      <%= form_with(model: @event, url: individual_shifts_path, remote: true) do |f| %>
         <%= render 'shared/error_messages', object: f.object %>

        <div class="form-inline text-left">
         <%= f.label :start,"出勤時刻", {class:'control-label'}%>
         <%= f.datetime_select :start, {default: Date.today + 0.hours + 00.minutes, minute_step: 60}, class: 'form-control bootstrap-date mb-3' %>
        </div>
         <br>
        <div class="form-inline text-left"> 
         <%= f.label :finish,"退勤時刻", {class:'control-label'}%>
         <%= f.time_select :finish, {default: Date.today + 0.hours + 00.minutes, minute_step: 60}, class: 'form-control' %>
        </div>
        <% if @patterns.count > 0 %>
            <% @patterns.each do |pattern| %>
                  <li class="pattern btn btn-danger" value="<%= pattern.start_h %>,<%= pattern.finish_h%>">
                        <%= pattern.start_to_finish %>
                  </li> 
            <% end %>
        <% end %>    
        <%= f.submit "登録",   class: "btn btn-primary js-event-create-btn" %>
      <% end %>
</div>      

<%= javascript_pack_tag 'individual_shifts/auto_shift' %>

app/views/individual_shifts/create.js.erb
$('#modal').fadeOut();
$('.response-modal-body').html('<h1>登録が完了しました！</h1>');
$('#response-modal').fadeIn();
<%# $('#calendar').fullCalendar( 'render' ); %>

app/views/individual_shifts/destroy.js.erb
    $('#modal').fadeOut();
    $('.response-modal-body').html('<h1>削除しました</h1>');
    $('#response-modal').fadeIn();
    <%# $('#calendar').fullCalendar( 'rerenderEvents' );
    $('#calendar').fullCalendar( 'addEventSource' ); %>

app/views/individual_shifts/index.html.erb
<div class="wrapper">
  <div class="open_title">
    <h1>シフト提出中</h1>
  </div>
  <div class ="submit">
    <%= link_to "終了する", finish_individual_shifts_path, method: :post, class:"btn btn-primary", data: { confirm: '終了してよろしいですか？(追加登録は可能です)' } %>
  </div>
  <% if current_staff.training_mode == true %>
    <div id="navi_open" class="navi">
      <label class="toggle" for="navi-open"><i class="fas fa-angle-double-right" aria-hidden="true"></i></label>
      <input id="navi-open" type="checkbox">
      <div id="navi">
        <nav>
          <ul>
            <li>
              <div class="title">
                <p>シフトの時間割</p>
                <label class="toggle" for="navi-close"><i class="fas fa-times"></i></label>
                <input id="navi-close" type="checkbox">
              </div>
              <% @shift_separation.each do |shift|%>
                <li>
                  <%= shift.name %>
                  <%= shift.start_time.strftime("%H:%M")%>~<%= shift.finish_time.strftime("%H:%M") %>
                </li>
              <% end %>
          </ul> 
        </nav>
      </div>   
    </div>  
  <% end %>
           
  <div id="calendar"></div>

  <div id="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
        </div>
      </div>
    </div>
  </div>
</div>  

<div id="response-modal" tabindex="0" role="dialog">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="error" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="response-modal-body">
        </div>
      </div>
    </div>
</div>

<%= javascript_pack_tag 'individual_shifts/calendar' %>
<%= javascript_pack_tag 'shared/index' %>