config/routes.rb
Rails.application.routes.draw do

  root 'perfect_shifts#index'
  get '/help',      to: 'static_pages#help'
  get  '/signup',   to: 'masters#new'
  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  post '/logout',    to:'sessions#destroy'

  resources :masters do
    patch     :shift_onoff   , on: :collection
    resources :shift_separations, :except => [:show]

    member do
      get :login,  to: 'masters#login_form'
      post :login, to: 'masters#login'
      delete :logout
    end
  end

  resources :staffs 

  resources :notices, :only => [:index, :show, :destroy, :update] do
    # patch :deny, on: :member
  end

  # get :chnage_form,      to: 'perfect_shifts#change_form'
  # patch :change,         to: 'perfect_shifts#change'

  resources :perfect_shifts, :only => [:index] do
    collection do
      get :fill
      get :change
      get :new_plan
      post :create_plan
    end

    member do
      patch :fill_in
      patch :instead
      patch :delete
    end
  end

  get :comfirmed_shifts,  to: 'comfirmed_shifts#index'

  resources :temporary_shifts , :only => [:index, :destroy] do
    collection do
      get :new_shift
      get :new_plan
      post :create_shift
      post :create_plan
      get  :delete
      patch :perfect
    end
    
    member do
      patch :deletable
    end
  end

  resources :deletable_shifts, :only => [:index] do
    get :restore , on: :collection
    patch :reborn, on: :member
  end
  
  resources :individual_shifts do
    
    collection do
      # patch  :confirm,  to: 'individual_shifts#confirm'
      patch  :perfect
      get  :remove
      post :finish
    end

    member do
      patch :deletable, to: 'individual_shifts#deletable'
    end
  end

end

app/controllers/perfect_shifts_controller.rb
class PerfectShiftsController < ApplicationController
  def index
    #このページで全てのアクションを起こす
    if logged_in?
        @events = current_master.individual_shifts.where(Temporary: true)
    end

    if logged_in_staff?
        @master = current_staff.master
        @events = @master.individual_shifts.where(Temporary: true)
        @shift_separation = @master.shift_separations.all
    end
  end

  #終日予定を追加するmodalを表示
  def new_plan
    if logged_in?
      @event = current_master.individual_shifts.new
      return_html("form_new_plan")
    else
      return_html("alert")
    end
  end

  #終日予定を追加処理
  def create_plan
    @event = current_master.individual_shifts.new(params_plan)
    @event.staff = current_master.staffs.find_by(staff_number: 0)
    @event.Temporary = true
    @event.save
    respond_to do |format|
      format.html { redirect_to temporary_shifts_path }
      format.js
    end
  end

  #空きシフトを埋めるmodalを表示
  def fill
    #両方ログイン中
    if logged_in? && logged_in_staff?
      fill_form_master

    #従業員のみログイン時
    elsif !logged_in? && logged_in_staff?
      @event = current_staff.master.individual_shifts.find(params[:shift_id])
      @already_event = current_staff.individual_shifts.find_by(start: @event.start)
      #シフトが重複しない用にする
      if @already_event.nil?
        return_html("form_fill")
      else
        return_html("alert")
      end

    #店長のみログイン時
    elsif logged_in? && !logged_in_staff?
      fill_form_master
    
    end
  end

  #空きシフトを埋める処理
  def fill_in
    #両方ログイン中
    if logged_in? && logged_in_staff?
      #従業員を店長に設定
      fill_in_master

    #従業員のみログイン時
    elsif !logged_in? && logged_in_staff?
      #ログイン中の従業員が空きシフトを埋める
      @master = current_staff.master
      @event = @master.individual_shifts.find(params[:id])
      @event.staff = current_staff

    #店長のみログイン時
    elsif logged_in? && !logged_in_staff?  
      #従業員を店長に設定
      fill_in_master
    end
    
    @event.save
  end

  #シフトの変更のmodalを表示
  def change
    begin
      #両方ログイン時
      if logged_in? && logged_in_staff?
        @event = current_master.individual_shifts.find(params[:shift_id])
        #終日の予定をクリックした時

        masters_action

      #従業員のみログイン時
      elsif !logged_in? && logged_in_staff?
        @event = current_staff.master.individual_shifts.find(params[:shift_id])
        @already_event = current_staff.individual_shifts.find_by(start: @event.start)
        #終日判定
        unless @event.allDay
          #他人のシフトをクリック
          if @event.staff != current_staff 
            #シフト重複を避ける
            if @already_event.present?
              return_html("alert")
            else
              #モードによってmodalのhtmlを変更する
              change_modal('form_instead', 'alert', 'alert')
            end
            
          # 自分の予定の場合
          elsif @event.staff == current_staff
            #モードによってmodalのhtmlを変更する
            change_modal('form_delete','already_delete', "already_instead")
          end
        else
          return_html("alert")
        end

      #店長のみログイン時
      elsif logged_in? && !logged_in_staff?
        @event = current_master.individual_shifts.find(params[:shift_id])
        #終日の予定をクリックした時

        masters_action
      end
    rescue => exception
      #何もしない(祝日イベント対策)
    end
    
  end

  #交代申請処理
  def instead
    #シフトのモードを変更、通知を作成、メール送信
    notice("instead")
  end

  #削除申請処理
  def delete
    #シフトのモードを変更、通知を作成、メール送信
    notice("delete")
  end

  private

    #店長ログイン時の空きシフトに入るためのmodal
    def fill_form_master
      @event = current_master.individual_shifts.find(params[:shift_id])
      #重複を避ける
      @master_staff = current_master.staffs.find_by(staff_number: current_master.staff_number)
      @already_event = @master_staff.individual_shifts.where(start:@event.start)
      unless @already_event.present?
        return_html("form_fill")
      else
        return_html("alert")
      end
    end

    #空きシフトに店長が入る処理
    def fill_in_master
      @event = current_master.individual_shifts.find(params[:id])
      @event.staff = current_master.staffs.find_by(staff_number:current_master.staff_number)
    end

    #変更に関して店長ができることを表示する
    def masters_action
      unless @event.allDay
        #店長権限でシフトをダイレクトに削除する
        return_html("form_direct_delete")
      else
        return_html("plan_delete")
      end
    end

    def params_notice
      params.require(:individual_shift).permit(:comment)
    end

    def params_plan
      params.require(:individual_shift).permit(:plan, :start)
    end

    #シフトのモードを変更、通知を作成、メール送信
    def notice(mode)
      @master = current_staff.master

      @event = @master.individual_shifts.find(params[:id])
      @event.mode = mode
      @event.save

      #通知を作成
      @notice = @master.notices.new
      @notice.mode = mode
      @notice.staff_id = current_staff.id
      @notice.shift_id = @event.id
      @notice.save

      #メール機能がオンなら通知を送信
      if @master.onoff_email
      NoticeMailer.send_when_create_notice(@notice).deliver
      end
    end

    #シフトのmodeによって表示するmodalを変更する
    def change_modal(nil_html,delete,instead)
      if @event.mode.nil?
        return_html(nil_html)
      elsif @event.mode == "delete"
        return_html(delete)
      elsif @event.mode == "instead"
        return_html(instead)
      end
    end
end

app/helpers/perfect_shifts_helper.rb
module PerfectShiftsHelper
    #指定したmodal用のhtmlを返す
    def return_html(html)
        render plain: render_to_string(partial: html, layout: false, locals: { event: @event })
    end
end

app/views/perfect_shifts/_alert.html.erb
<p>操作はできません</p>

app/views/perfect_shifts/_already_delete.html.erb
<p>既に削除申請は提出済みです</p>
<p>店長の指示を待ちましょう</p>

app/views/perfect_shifts/_already_instead.html.erb
<p>既に交代申請は提出されています</p>
<p>店長の指示を待ちましょう</p>

app/views/perfect_shifts/_form_delete.html.erb
<h1><%= @event.time %></h1>

<div class="row">
      <%= form_with(model: @event, url: delete_perfect_shift_path(@event), html: {method: :patch},remote: true) do |f| %>
         <%= f.label      :comment, "削除理由" %>
         <%= f.text_area :comment, class: 'form-control' %>
         <%= f.submit "削除申請",   class: "btn btn-primary js-event-create-btn" , data: { confirm: '本当に削除申請してよろしいですか?' } %>
      <% end %>
</div>        

app/views/perfect_shifts/_form_direct_delete.html.erb
<h1><%= @event.staff.staff_name %></h1>
<%= render 'individual_shifts/form_delete' %>  

app/views/perfect_shifts/_form_fill.html.erb
<div class="row">
      <%= form_with(model: @event, url: fill_in_perfect_shift_path(@event), html: {method: :patch},remote: true) do |f| %>
         <%= f.submit "シフトに入る",   class: "btn btn-primary js-event-create-btn" %>
      <% end %>
</div>        

app/views/perfect_shifts/_form_instead.html.erb
<h1><%= @event.staff.staff_name %> <%= @event.time %></h1>
<div class="row">
      <%= form_with(model: @event, url: instead_perfect_shift_path(@event), html: {method: :patch},remote: true) do |f| %>
         <%= f.submit "交代する",   class: "btn btn-primary js-event-create-btn", data: { confirm: '交代したいシフトは合っていますか?' }%>
      <% end %>
</div>        

app/views/perfect_shifts/_form_new_plan.html.erb
<h1>営業•催事</h1>

<div class="row master_plan"> 
      <%= form_with(model: @event, url: create_plan_perfect_shifts_path, remote: true) do |f| %>
         <%= render 'shared/error_messages', object: f.object %>       
         <%= f.label :plan, "内容"%>
         <%= f.text_field :plan, class:'form-control mb-3', required: true %>
        <div class="form-inline text-left">
         <%= f.label :start,"日付", {class:'control-label'}%>
         <%= f.date_select :start, {default: Date.today}, class: 'form-control bootstrap-date mb-3' %>
        </div>
         <br>
         <%= f.submit "登録",   class: "btn btn-primary js-event-create-btn" %>
      <% end %>
</div>        

app/views/perfect_shifts/_info_event.html.erb
<%= @event.id %>
<p>空き</p><br>
<%= @event.start.strftime("%H:%M") %><br>
<%= @event.finish.strftime("%H:%M")%>

app/views/perfect_shifts/_plan_delete.html.erb
<h1><%= @event.plan %></h1>

<div class="row">
    <%= form_with(model: @event, url: individual_shift_path(@event), html: { method: :delete }, remote: true) do |f| %>
        <%= f.submit "消去", class: "btn btn-primary" %>
    <% end %>
</div>    

app/views/perfect_shifts/create_plan.js.erb
$('#modal').fadeOut();
$('.response-modal-body').html('<h1>登録完了しました！</h1>');
$('#response-modal').fadeIn();
$('#calendar').fullCalendar( 'render' );

app/views/perfect_shifts/delete.js.erb
$('#modal').fadeOut();
$('.response-modal-body').html('<h1>削除申請をしました！</h1>');
$('#response-modal').fadeIn();
$('#calendar').fullCalendar( 'render' );

app/views/perfect_shifts/fill_in.js.erb
$('#modal').fadeOut();
$('.response-modal-body').html('<h1>イエローラインを埋めました！</h1>');
$('#response-modal').fadeIn();
$('#calendar').fullCalendar( 'render' );

app/views/perfect_shifts/index.html.erb
<div class="wrapper">
        <div class="shift_onoff">
            <% if logged_in? %>
            <%if current_master.shift_onoff == false %>
                        <%= link_to "募集を開始する",shift_onoff_masters_path, method: :patch, class: "btn btn-primary" %>
                    <% else %>
                        <%= link_to "募集を終了する",shift_onoff_masters_path, method: :patch, class: "btn btn-danger" %>
                    <% end %>
            <% end %> 
        </div>
        <% if logged_in_staff? || logged_in?%>  
            <div class = "create_plan">
                <% if logged_in? %>
                    <button type="button" name="name" class="plan btn btn-primary">営業•催事を追加する</button>
                <% end %> 
            </div>
        <% if !logged_in? && logged_in_staff? %>
          <div class="gap-root"></div>
        <% end %>

        <div class="training">
            <p>トレーニング中</p>
        </div>
        <div class="normal">
            <p>通常</p>
        </div>
        <div class="all-calendar">
            <div id="calendar"></div>
        </div>

        <div id="modal" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                    </div>
                </div>
            </div>
        </div>

        <div id="response-modal" tabindex="0" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="error" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="response-modal-body">
                    </div>
                </div>
            </div>
        </div>
    <% else %>
        <%= render 'static_pages/how_to_use' %>
    <% end %>   
</div>    

<%= javascript_pack_tag 'perfect_shifts/calendar' %>
<%= javascript_pack_tag 'shared/index' %>