config/routes.rb
Rails.application.routes.draw do

  root 'perfect_shifts#index'
  get '/help',      to: 'static_pages#help'
  get  '/signup',   to: 'masters#new'
  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  post '/logout',    to:'sessions#destroy'

  resources :masters do
    patch     :shift_onoff   , on: :collection
    resources :shift_separations, :except => [:show]

    member do
      get :login,  to: 'masters#login_form'
      post :login, to: 'masters#login'
      delete :logout
    end
  end

  resources :staffs 

  resources :notices, :only => [:index, :show, :destroy, :update] do
    # patch :deny, on: :member
  end

  # get :chnage_form,      to: 'perfect_shifts#change_form'
  # patch :change,         to: 'perfect_shifts#change'

  resources :perfect_shifts, :only => [:index] do
    collection do
      get :fill
      get :change
      get :new_plan
      post :create_plan
    end

    member do
      patch :fill_in
      patch :instead
      patch :delete
    end
  end

  get :comfirmed_shifts,  to: 'comfirmed_shifts#index'

  resources :temporary_shifts , :only => [:index, :destroy] do
    collection do
      get :new_shift
      get :new_plan
      post :create_shift
      post :create_plan
      get  :delete
      patch :perfect
    end
    
    member do
      patch :deletable
    end
  end

  resources :deletable_shifts, :only => [:index] do
    get :restore , on: :collection
    patch :reborn, on: :member
  end
  
  resources :individual_shifts do
    
    collection do
      # patch  :confirm,  to: 'individual_shifts#confirm'
      patch  :perfect
      get  :remove
      post :finish
    end

    member do
      patch :deletable, to: 'individual_shifts#deletable'
    end
  end

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-expand-lg mr-auto">
   <div class="container">
      <%= link_to "セブンルール", root_path, id: "logo" %>
      <% if logged_in? || logged_in_staff? %>
         <div id="menu_open" class="menu">
            <label class="toggle" for="open"><i class="fa fa-bars" aria-hidden="true"></i></label>
            <input id="open" type="checkbox">
            <div id="menu">
               <nav>
                  <ul>
                     <li>
                        <div class="store_info">
                           <label class="toggle" for="close"><i class="fas fa-times"></i></label>
                           <input id="close" type="checkbox">
                           <% if logged_in? && logged_in_staff?%>
                              <h1><%= current_master.store_name %></h1>
                           <% elsif !logged_in? && logged_in_staff?  %>
                              <h1><%= current_staff.master.store_name %></h1>
                           <% elsif logged_in? && !logged_in_staff? %>
                              <h1><%= current_master.store_name %></h1>
                           <% end %>
                        </div>
                     </li>
                     <li><%= link_to "ヘルプ", help_path, class:"help" %></li>
                     <div class="line"></div>
                     
                     <% if logged_in? && logged_in_staff? %>
                        <%= render "layouts/menu_master" %>
                        <br>
                        <div class="line"></div>
                        <%= render "layouts/menu_staff" %>
                     <% elsif !logged_in? && logged_in_staff? %>
                        <%= render "layouts/menu_staff" %>
                     <% elsif logged_in? && !logged_in_staff? %>  
                        <%= render "layouts/menu_master" %>
                     <% end %>  
                  </ul>
               </nav>
            </div>   
         </div>
      <% else %>
         <div class="nav-btn">
            <%= link_to "新規登録", signup_path, class:"btn btn-lg btn-danger signup" %> 
            <%= link_to "店長ログイン", login_path,class:"btn btn-lg btn-primary login" %> 
         </div>
      <% end %>
   </div>   
</header>   
    
    

app/views/layouts/_menu_master.html.erb
<p>店長</p>
<h1>
    <%= current_master.user_name %> さん
</h1>
<li><%= link_to "ユーザー情報を変更する", edit_master_path(current_master) %> </li>
<li><%= link_to "従業員登録", new_staff_path %> </li>
<li><%= link_to "従業員一覧", staffs_path %></li>
<li><%= link_to "シフト時間割を追加する", new_master_shift_separation_path(current_master)%></li>
<li><%= link_to "シフト時間割一覧", master_shift_separations_path(current_master) %> </li>
<li><%= link_to "スタッフとしてログインする", login_master_path(current_master) %></li>
<% if current_master.shift_onoff == false %>
  <li><%= link_to "シフトを調整する", temporary_shifts_path %></li>
<% end %>
<li>
    <div class="notice">
        <%= link_to "通知", notices_path%>
        <div class="number">
            <span><%= current_master.notices.count %></span>
        </div>
    <div>
</li> <br><br><br>
<li>
    <%= link_to "ログアウト", logout_path, {:method=> :post, class:"logout"} %>
</li>  
<div class="line"></div>
<li>
    <div class="form-group">
        <p>urlを従業員に共有しましょう</p>
        <input class="border border-info rounded text-secondary form-control " id="CopyTarget" 
            type="text" value="http://localhost:3000/masters/<%= current_master.id%>/login" readonly>
        <div class="copy">
            <button type="button" class="btn btn-info " id="copy" data-toggle="tooltip" data-placement="top" title="コピーする">
                <i class="fas fa-clipboard"></i>
            </button>
            <p>←こちらをクリック</p>
        </div>
    </div>
</li>   

app/views/layouts/_menu_staff.html.erb
<p>従業員</p>  
<h1>
    <%= current_staff.staff_name %> さん
</h1>
<li><%= link_to "ユーザー情報を変更する", edit_staff_path(current_staff)%></li>
<% if current_staff.master.shift_onoff == true %>
    <li><%= link_to "シフトを提出する",individual_shifts_path %></li>
<% end %>  
<li><%= link_to "シフトを確認する", comfirmed_shifts_path %></li>
<% unless logged_in? && Rails.env.development? %>
  <li><%= link_to "店長ログイン", login_path %></li>
<% end %>

<li><%= link_to "ログアウト", logout_master_path(current_staff), {:method=> :delete, class:"logout"} %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>convenience-shift</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
</head>

  <body data-turbolinks="false">
    <%= render 'layouts/header' %>
    <div id="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%# <%= debug(params) if Rails.env.development? %> 
    </div>  
  </body>
</html>